### ISSUE TITLE
Please do not append /0 in REDIS_URL

### ISSUE THREAD

**Issue by sglebs** [sekjun9878/dokku-redis-plugin#25]
Hi,

   On heroku, REDIS_URL (say Open Redis) is never defined with the database number at the end (/0). This allows one to define sub-areas by just appending /N to REDIS_URL. Therefore, I would like to suggest that you no longer do this:

KEY="REDIS_URL"
VALUE="redis://redis:6379/0"

but instead do this:

KEY="REDIS_URL"
VALUE="redis://redis:6379"

So that apps can be run on heroic or on dock with no changes regarding REDIS.

Thanks for listening.

**Comment by msjyoo** [comment]
Hmm I see. I do not use Heroku myself and the suggestion was taken from this pull request: https://github.com/sekjun9878/dokku-redis-plugin/pull/8/files. I will look into fixing this. Thanks for reporting!

**Comment by sglebs** [comment]
It is in libconfig.
