### ISSUE TITLE
docker linking does not seem to work

### ISSUE THREAD

**Issue by sglebs** [sekjun9878/dokku-redis-plugin#29]
I am using supervisord to launch a unicorn/python ("core-server") and a celeryd, which interact with each other via Redis (your plugin). celeryd is bombing, failing to connect. So, I decided to check core-server's /etc/hosts:

```
root@dokku:/var/lib/dokku/plugins# docker ps
CONTAINER ID        IMAGE                      COMMAND                CREATED              STATUS              PORTS               NAMES
f81467ed840b        dokku/core-server:latest   "/start web"           About a minute ago   Up About a minute                       sick_jones              
9108b121f42c        redis:latest               "/entrypoint.sh redi   27 minutes ago       Up 27 minutes       6379/tcp            redis-core-server       
f0794698c0d9        mdillon/postgis:latest     "/docker-entrypoint.   43 minutes ago       Up 43 minutes       5432/tcp            psql-single-container   

root@dokku:/var/lib/dokku/plugins# docker commit f81467ed840b mysnapshot
f4f981ea6ff99a7fda5b19fc29e7e4ee84d889b12e78456b61f94d3a7a27df44

root@dokku:/var/lib/dokku/plugins# docker run -t -i mysnapshot /bin/bash

root@685035caf472:/# cat /etc/hosts
172.17.0.36 685035caf472
127.0.0.1   localhost
::1 localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
root@685035caf472:/# 
```

No "redis" in /etc/hosts. Any idea?

**Comment by sglebs** [comment]
In https://github.com/sekjun9878/dokku-redis-plugin/blob/master/pre-build I do see the removal:

dokku docker-options:remove "$APP" deploy,run "--link $REDIS_CONTAINER_NAME:redis"

In https://github.com/sekjun9878/dokku-redis-plugin/blob/master/pre-release I do see it being added:

dokku docker-options:add "$APP" deploy,run "--link $REDIS_CONTAINER_NAME:redis"

Bizarre.

**Comment by sglebs** [comment]
I also noticed these vars are not set:

```
# Default Docker Link variables
REDIS_NAME=/<random_docker_generated_container_name>/redis
REDIS_PORT=tcp://<IPv4 Address>:6379
REDIS_PORT_6379_TCP=tcp://<IPv4 Address>:6379
REDIS_PORT_6379_TCP_PROTO=tcp
REDIS_PORT_6379_TCP_PORT=6379
REDIS_PORT_6379_TCP_ADDR=<IPv4 Address>
```

I did ps:restart my app. Any chance the values are not re-injected on restart?

**Comment by sglebs** [comment]
I believe that a restart is not re-injecting these values:

```
(core-server)Marcio-Marchinis-MacBook-Pro-Silver:core-server mqm$ ssh dokku@10.10.10.10 ps:restart  core-server
-----> Releasing core-server ...
-----> Preparing Redis for core-server...
-----> Redis container linked: core-server -> redis-core-server
-----> Creating Redis autoconfiguration environment variable
-----> Deploying core-server ...
-----> Starting Redis for core-server...
       Redis container already running: redis-core-server
-----> Running pre-flight checks
       CHECKS file not found in container: running simple container check...
-----> Waiting for 35 seconds ...
```

It detects it already running. Perhaps it is not injecting in this case - a mistake for sure.

**Comment by msjyoo** [comment]
Hello,

Can you tell me the version number of your Dokku and the commit hash of my redis plugin?

I haven't yet tested the newest changes on master (on a live machine - they looked fine on code) so if you are running on master instead of latest stable tag, then I can't be sure that it works.

As far as I know the plugin v1.0.0 works stably on Dokku 0.3.15.

**Comment by msjyoo** [comment]
Any update on the issue?

**Comment by 3onyc** [comment]
@sglebs is your app using Dockerfiles or buildpacks?

I'm observing the same issue with Dockerfile based apps, currently fixing it, a pull request should appear soon ;)

**Comment by msjyoo** [comment]
Hello. Please try the latest version v1.0.1 on Dokku v0.3.17. The issue should have been fixed.
