### ISSUE TITLE
Enable redis as an LRU cache?

### ISSUE THREAD

**Issue by sglebs** [sekjun9878/dokku-redis-plugin#33]
Hi, thanks for the plugin!

How can I enable the redis for app X to be LRU and a max of say 2MB when I use your plugin?

I mean this: 

http://redis.io/topics/config#configuring-redis-as-a-cache
Configuring Redis as a cache
If you plan to use Redis just as a cache where every key will have an expire set, you may consider using the following configuration instead (assuming a max memory limit of 2 megabytes as an example):

maxmemory 2mb
maxmemory-policy allkeys-lru

Can I override the config of these 2 attributes?

Thanks!

**Comment by msjyoo** [comment]
I'll solve this issue by allowing custom configuration of the redis image used. So you could create your own docker image with your configuration options as described here: https://hub.docker.com/_/redis/. Would that solve the problem?

**Comment by sglebs** [comment]
The easy and high level way for clients like me it would be to set an env var which points at the config file. Example:

```
dokku config:set myapp REDIS_CONFIG=myconfig.cfg
```

But I am not sure you can have access to it? It would be nice this way because it would allow each app to customize itself.

If I understand what you are saying, I would have a custom docker file say  ./myredis/Dockerfile which I somehow would pass to you (via cmd-line, I suppose). In this file I would have:

```
FROM redis
COPY redis.conf /usr/local/etc/redis/redis.conf
CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
```

Is that it?

I find it a bit low level. On Heroku, OpenRedis provides a simple web GUI where I can set those values.

Another alternative would be for me to provide redis config commands in an env var. Example:

REDIS_CONFIG_CMDS=cmd1;cmd2;cmd3;....

The commands would be the ones for CONFIG: http://redis.io/topics/config#changing-redis-configuration-while-the-server-is-running , http://redis.io/commands/config-set

Example: REDIS_CONFIG_CMDS="timeout 10;maxmemory-policy allkeys-lru;maxmemory 2mb"

So, every time you fire up or restart the server for app X, you would invoke those commands for the app. Would  that work? It would be the simplest for clients to use. I am guessing I would be able to set all sorts of things?

**Comment by sglebs** [comment]
ping

**Comment by msjyoo** [comment]
Hello. Sorry, I haven't had the time to implement this here. However, there has been an official remake of the Redis plugin which I would like to refer you to, if they support configuration like you mention.

That plugin will eventually succeed this one being the official datastore plugin and all so...

Give me a few days to sort this out. Thanks!

**Comment by msjyoo** [comment]
Right, so the Dokku redis plugin supports configuration, and is an all-round better supported plugin.

Please consider migrating to https://github.com/dokku/dokku-redis for new projects and if you need a better feature set.

I made this to "scratch my own itch" but it's hard to beat "officially supported"!

Thanks!
